##===- unittests/ExecutionEngine/JIT/Makefile --------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..
TESTNAME = SinglePath
LINK_COMPONENTS := PatmosSinglePath

include $(LEVEL)/Makefile.config

SOURCES := PredicatedBlockTest.cpp 

include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest
