##===- unittests/ExecutionEngine/Makefile ------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
TESTNAME = PatmosUnitTests
LINK_COMPONENTS :=

PARALLEL_DIRS = SinglePath

include $(LEVEL)/Makefile.common
include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest
